### ISSUE TITLE
Estimation of tumor purity and ploidy

### ISSUE THREAD

**Issue by pigyun906** [wwylab/TmS#1]
Hi, thank you for developing a useful tool.
I'm interested in the TmS you suggested using bulk whole-exome and RNA sequencing.

I have some questions during the tutorial to reproduce the results.
I understand that I need to manually estimate tumor purity and ploidy using ASCAT and ABSOLUTE to obtain the TmS.

#1. What tools and options should I use to make input files for ASCAT and ABSOLUTE?
#2. And, Is there no correlation between TmS and tumor purity and ploidy obtained using sequenza?

Thank you

**Comment by jiyunmaths** [comment]
Hi @pigyun906, thanks for your interest about TmS. 
For tumor purity and ploidy estimates, the three methods (ASCAT, ABSOLUTE and Sequenza) need the matched DNAseq data (e.g., WES or WGS BAM files) from tumor and normal samples. They also have tool-specific inputs. For ASCAT, please visit its GitHub page for more information: https://github.com/VanLoo-lab/ascat. For ABSOLUTE, please visit https://software.broadinstitute.org/cancer/cga/absolute. 
For your second question, we do observe a strong correlation between the TmS values based on Sequenza and based on other methods, such as ASCAT. Thanks.

**Comment by pigyun906** [comment]
I satisfied my curiosity.
Thank you
