### ISSUE TITLE
Can I used for tumor-only bulk mRNA-seq?

### ISSUE THREAD

**Issue by kyle-lk** [wwylab/TmS#2]
Can I used for tumor-only bulk mRNA-seq?

**Comment by jiyunmaths** [comment]
Hi @kyle-lk  TmS calculation needs normal sample as the reference for bulk mRNA-seq deconvolution using DeMixT (https://github.com/wwylab/DeMixT). If you do not have RNA-seq data for the normal, we recommend you to use the normal sample data from TCGA or GTEx (https://gtexportal.org/home/) which are sequenced from the same tissue as your tumor RNA-seq data.  Thanks.

**Comment by jiyunmaths** [comment]
The question was addressed.
